server:
  port: 8683
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://service-eureka
          predicates:
          - Path=/eureka/**
          filters:
          - StripPrefix=1
          - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: path_demo
          uri: lb://demo
          predicates:
          - Path=/demo/**
          filters:
          - StripPrefix=1
          - AddResponseHeader=X-Response-Default-Foo, Default-Bar
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: localhost